# Generated by Django 5.0.6 on 2024-05-24 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perpustakaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perpustakaan', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('pengarang', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='perpustakaan_api.genre')),
                ('perpustakaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan_api.perpustakaan')),
            ],
        ),
    ]
